name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print Success Message
      if: success()
      run: echo "Build successful!"
